# Generated by Django 4.2.23 on 2025-08-27 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('edit_time', models.DateTimeField(auto_now=True)),
                ('is_over', models.BooleanField(default=False)),
                ('country', models.SmallIntegerField(choices=[(0, '中国'), (1, '日本'), (2, '韩国'), (3, '其他')], default=0)),
                ('type', models.SmallIntegerField(choices=[(0, '音声'), (1, '视频音声'), (2, '视频'), (3, '图片'), (4, '其他')], default=0)),
                ('is_cast', models.BooleanField(default=False)),
                ('level', models.SmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('edit_time', models.DateTimeField(auto_now=True)),
                ('is_over', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ChineseAsmr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('duration', models.IntegerField()),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('edit_time', models.DateTimeField(auto_now=True)),
                ('level', models.SmallIntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.author')),
                ('next', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.chineseasmr')),
            ],
        ),
        migrations.AddField(
            model_name='author',
            name='studio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.studio'),
        ),
    ]
