# Generated by Django 4.2.23 on 2025-08-30 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='alias',
            field=models.CharField(max_length=100, null=True, verbose_name='作者别名'),
        ),
        migrations.AlterField(
            model_name='author',
            name='add_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='author',
            name='country',
            field=models.SmallIntegerField(choices=[(0, '中国'), (1, '日本'), (2, '韩国'), (3, '其他')], default=0, verbose_name='作者国家'),
        ),
        migrations.AlterField(
            model_name='author',
            name='description',
            field=models.TextField(null=True, verbose_name='作者描述'),
        ),
        migrations.AlterField(
            model_name='author',
            name='edit_time',
            field=models.DateTimeField(auto_now=True, verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='author',
            name='is_cast',
            field=models.BooleanField(default=False, verbose_name='是否是主播'),
        ),
        migrations.AlterField(
            model_name='author',
            name='is_over',
            field=models.BooleanField(default=False, verbose_name='是否结束'),
        ),
        migrations.AlterField(
            model_name='author',
            name='level',
            field=models.SmallIntegerField(default=0, verbose_name='作者等级'),
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=20, verbose_name='作者名称'),
        ),
        migrations.AlterField(
            model_name='author',
            name='studio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.studio', verbose_name='工作室名称'),
        ),
        migrations.AlterField(
            model_name='author',
            name='type',
            field=models.SmallIntegerField(choices=[(0, '音声'), (1, '视频音声'), (2, '视频'), (3, '图片'), (4, '其他')], default=0, verbose_name='作者类型'),
        ),
        migrations.AlterField(
            model_name='chineseasmr',
            name='add_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='chineseasmr',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.author', verbose_name='作者名称'),
        ),
        migrations.AlterField(
            model_name='chineseasmr',
            name='description',
            field=models.TextField(verbose_name='asmr描述'),
        ),
        migrations.AlterField(
            model_name='chineseasmr',
            name='duration',
            field=models.IntegerField(null=True, verbose_name='asmr时长'),
        ),
        migrations.AlterField(
            model_name='chineseasmr',
            name='edit_time',
            field=models.DateTimeField(auto_now=True, verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='chineseasmr',
            name='level',
            field=models.SmallIntegerField(default=0, verbose_name='asmr等级'),
        ),
        migrations.AlterField(
            model_name='chineseasmr',
            name='name',
            field=models.CharField(max_length=100, verbose_name='asmr名称'),
        ),
        migrations.AlterField(
            model_name='chineseasmr',
            name='next',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.chineseasmr', verbose_name='下一集名称'),
        ),
        migrations.AlterField(
            model_name='studio',
            name='add_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='studio',
            name='description',
            field=models.TextField(null=True, verbose_name='工作室描述'),
        ),
        migrations.AlterField(
            model_name='studio',
            name='edit_time',
            field=models.DateTimeField(auto_now=True, verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='studio',
            name='is_over',
            field=models.BooleanField(default=False, verbose_name='是否结束'),
        ),
        migrations.AlterField(
            model_name='studio',
            name='name',
            field=models.CharField(max_length=20, verbose_name='工作室名称'),
        ),
    ]
