# Generated by Django 4.2.23 on 2025-08-30 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_author_alias_alter_author_add_time_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': '作者', 'verbose_name_plural': '作者'},
        ),
        migrations.AlterModelOptions(
            name='chineseasmr',
            options={'verbose_name': 'asmr', 'verbose_name_plural': 'asmr'},
        ),
        migrations.AlterModelOptions(
            name='studio',
            options={'verbose_name': '工作室', 'verbose_name_plural': '工作室'},
        ),
    ]
