# Generated by Django 4.2.23 on 2025-08-30 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_author_options_alter_chineseasmr_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='作者描述'),
        ),
        migrations.AlterField(
            model_name='chineseasmr',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='asmr描述'),
        ),
        migrations.AlterField(
            model_name='studio',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='工作室描述'),
        ),
    ]
