# Generated by Django 4.2.23 on 2025-08-30 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_author_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='alias',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='作者别名'),
        ),
    ]
